trigger:
  branches:
    include:
      - main (caminho para a main dev)

pool:
  vmImage: ubuntu-latest
strategy:
  matrix:
    Python38:
      python.version: '3.8'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Usando Versão Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Instalando dependências'

- script: |
    robot -d ./results -i pipeline ./tests
  displayName: 'Run Testes'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(System.DefaultWorkingDirectory)/results/log.html'
    artifact: 'Artifacts'    
  displayName: 'Publicando Artefatos'